"""created-tables

Revision ID: 77a063f61826
Revises:
Create Date: 2021-05-05 16:23:22.053843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a063f61826'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=40),
                              nullable=False),
                    sa.Column('first_name', sa.String(length=100),
                              nullable=True),
                    sa.Column('last_name', sa.String(length=100),
                              nullable=True),
                    sa.Column('email', sa.String(length=255),
                              nullable=False),
                    sa.Column('avatar_url', sa.String(length=256),
                              nullable=True),
                    sa.Column('hashed_password', sa.String(length=255),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('library_links',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=55), nullable=True),
                    sa.Column('library_link_url', sa.String(length=256),
                              nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('notebooks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=55), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('private', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('notes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=55), nullable=False),
                    sa.Column('content', sa.Text(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('notebook_id', sa.Integer(), nullable=True),
                    sa.Column('private', sa.Boolean(), nullable=True),
                    sa.Column('notes_url', sa.String(length=255),
                              nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
                    sa.ForeignKeyConstraint(['notebook_id'],
                                            ['notebooks.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    op.drop_table('notebooks')
    op.drop_table('library_links')
    op.drop_table('users')
    # ### end Alembic commands ###
